[package]
name = "adorabot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scylla = "0.4.7"
tokio = "1.19.2"

[[bin]]
name="stats"
path = "rust-src/stats.rs"
